### ISSUE TITLE
Adopt RSCSS

### ISSUE THREAD

**Issue by joeljuca** [alinembl/ProjetoCefa#10]
[RSCSS](http://rscss.io) is a set of simple ideas to guide your process of building maintainable CSS. It provides naming conventions, rules, and a file structure for CSS codebases.

- [x] Convert partials into RSCSS modules #11
- [x] Ensure that class names are complying with RSCSS #12
- [x] Ensure that Pug files are using our new classes correctly #13

**Comment by joeljuca** [comment]
Congrats @alinembl! 🏆
